AppSecrets_properties_typeProperties_baseUrl: https://key1737.vault.azure.net/
AzureDataLakeStorage1_properties_typeProperties_url: https://synstr1737.dfs.core.windows.net/
AzureKeyVault1_properties_typeProperties_baseUrl : https://key17.vault.azure.net/
