# This is a basic workflow to help you get started with Actions.

name: Copy from dev to prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "syn-pipelines-dev-prod" branch
  push:
    branches: [ "dinesh_feature" ]
  #pull_request:
  #  branches: [ "dinesh_feature" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
      id-token: write
      contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    #runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run Git commands
        run: |
          rm rf sqldb18723
          & "C:\Program Files\Git\bin\git.exe" clone https://github.com/DineshChekuru/sqldb18723.git -b dinesh_feature

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: | 
            .\config.ps1
        
            # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest
            # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
          errorActionPreference: Stop

      - name: Run Git commands
        run: |
          cd sqldb18723
          "C:\Program Files\Git\bin\git.exe" git add .
         # "C:\Program Files\Git\bin\git.exe" commit -m "latest"
         # "C:\Program Files\Git\bin\git.exe" --force origin dinesh_feature
