# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "syn-pipelines-dev-prod" branch
  push:
    branches: [ "prod_qa" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
      id-token: write
      contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
              
      - name: CLI Login
        run: |
              az login --service-principal -u 'f55422ff-27d7-49e9-bac4-b2d08e348b1e' -p '51y8Q~Z65zXIl9VvlskSLdWF3wiqSnXgqH_yMb9f' --tenant 'd5d054a0-66ec-434f-88c2-0ac973a0dfb1'
              $synapsetrigger = az synapse trigger list --workspace-name synprod | ConvertFrom-Json
              foreach ($syn in $synapsetrigger) {
              if($syn.name -eq "Tiggerdev" -or $syn.name -eq "Triggersp"){
              az synapse trigger start --name $syn.name --workspace-name synprod
              }
              else{
              az synapse trigger start --name $syn.name --workspace-name synprod
              }
              }
              
#       - name: Synapse workspace deployment
#         uses: Azure/Synapse-workspace-deployment@V1.7.0
#         with:
#           TargetWorkspaceName: 'synprod'
#           OverrideArmParameters: ./parameters.yml
#           ArtifactsFolder: ./dev
#           Environment: 'Azure Public'
#           resourceGroup: 'dinesh'
#           clientId: 'f55422ff-27d7-49e9-bac4-b2d08e348b1e'
#           clientSecret: '51y8Q~Z65zXIl9VvlskSLdWF3wiqSnXgqH_yMb9f'
#           subscriptionId: '56542616-48a1-4fd4-a9e2-947518afe39b'
#           tenantId: 'd5d054a0-66ec-434f-88c2-0ac973a0dfb1'
#           operation: 'validateDeploy'
