# This is a basic workflow to help you get started with Actions.

name: Copy from dev to prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "syn-pipelines-dev-prod" branch
  push:
    branches: [ "dinesh_feature" ]
  #pull_request:
  #  branches: [ "dinesh_feature" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
      id-token: write
      contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    #runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run Git commands
        run: |
          & "C:\Program Files\Git\bin\git.exe" clone https://github.com/DineshChekuru/sqldb18723.git -b dinesh_feature
